using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.ComponentModel;
using System.Diagnostics;
using System.Globalization;
using System.Linq;
using System.Reflection;
using System.Resources;
using System.Runtime.CompilerServices;
using System.Text;
using System.Threading.Tasks;

namespace WinformsControls.Properties;

/// <summary>
///   A strongly-typed resource class, for looking up localized strings, etc.
/// </summary>
// This class was auto-generated by the StronglyTypedResourceBuilder
// class via a tool like ResGen or Visual Studio.
// To add or remove a member, edit your .ResX file then rerun ResGen
// with the /str option, or rebuild your VS project.
[GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
[DebuggerNonUserCodeAttribute()]
[CompilerGeneratedAttribute()]
internal sealed class Resources
{
	private ResourceManager _resourceManager;

	public Resources() 
    {
    }

    /// <summary>
    /// Returns the cached ResourceManager instance used by this class.
    /// </summary>
    [EditorBrowsableAttribute(EditorBrowsableState.Advanced)]
    public ResourceManager ResourceManager => InternalResourceManager;

    /// <summary>
    /// Overrides the current thread's CurrentUICulture property for all
    /// resource lookups using this strongly typed resource class.
    /// </summary>
    [EditorBrowsableAttribute(EditorBrowsableState.Advanced)]
    internal CultureInfo ResourceCulture { get; set; }

    /// <summary>
    /// Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    public Bitmap CalendarDark
    {
        get
        {
            string resourceName = nameof(CalendarDark);
            object obj = InternalResourceManager.GetObject(resourceName, ResourceCulture);
            
            if(obj != null && obj is Bitmap calendarDark)
            {
                return calendarDark;
            }

            return null;
        }
    }

    /// <summary>
    /// Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    public Bitmap CalendarWhite
    {
        get
        {
            string resourceName = nameof(CalendarWhite);
            object obj = InternalResourceManager.GetObject(resourceName, ResourceCulture);
            
            if(obj != null && obj is Bitmap calendarWhite)
            {
                return calendarWhite;
            }

            return null;
        }
    }

    private ResourceManager InternalResourceManager
    {
        get
        {
            if (_resourceManager == null)
            {
                Type resourceType = typeof(Resources);
                string resourceName = resourceType.FullName;
                Assembly resourceAssembly = resourceType.Assembly;

                _resourceManager = new ResourceManager(resourceName, resourceAssembly);
            }

            return _resourceManager;
        }
    }
}